config/routes.rb
Rails.application.routes.draw do
  resources :recipe_foods
  devise_for :users
  resources :users, only:[:index], shallow: true do
    resources :foods, only: [:index, :create, :new, :destroy]
    resources :recipes
  end
  resources :recipes do
    resources :recipe_foods, only: [:index, :new, :create, :update, :destroy]
  end
  resources :general_shopping_list, only: [:index]
  resources :public_recipes, only: [:index]
  root to: "public_recipes#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  # Associations
  belongs_to :user
  has_many :recipe_foods, foreign_key: :recipe_id, dependent: :destroy

  # Attributes
  attribute :name, :string
  attribute :preparation_time, :string
  attribute :cooking_time, :string
  attribute :description, :text
  attribute :public, :boolean

  # Validations
  validates :name, presence: true
  validates :description, presence: true
  validates :preparation_time, presence: true, numericality: { greater_than_or_equal_to: 0, only_float: true }
  validates :cooking_time, presence: true, numericality: { greater_than_or_equal_to: 0, only_float: true }
  validates :public, inclusion: [true, false]

  def totals
    recipe_foods.includes(:food).reduce({ price: 0, quantity: 0 }) do |acc, hash|
      {
        price: acc[:price] + hash.food.price,
        quantity: acc[:quantity] + hash[:quantity]
      }
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @recipes = @user.recipes
  end

  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html { render :new }
    end
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id

    respond_to do |format|
      format.html do
        if @recipe.save
          redirect_to recipe_path(@recipe), notice: 'The recipe was saved successfully!'
        else
          flash.now[:error] = 'Error: Recipe could not be saved'
          render :new
        end
      end
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_public_params)
      redirect_to recipe_path(@recipe), notice: 'Public status has been changed successfully.'
    else
      render :show, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path(user_id: current_user), notice: 'The food was deleted successfully!'
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time)
  end

  def recipe_public_params
    params.require(:recipe).permit(:public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_public_btn.html.erb
<%= form_with(model: recipe, local: true) do |f| %>
<div class="form-check form-switch">
    <%= f.label :public, class:"form-check-label"%>
     <%= f.check_box :public, class: "sr-only peer form-check-input", onchange: "this.form.requestSubmit();" %>
</div>
<% end %>

app/views/recipes/_recipe_foods_table.html.erb
<% if @recipe_foods.empty?%>
  <p class="text-primary">No ingredients added yet!</p>

<% else %>

<% if can? :manage, @recipe %>
  <div class="d-flex justify-content-between">
    <%= button_to "Generate Shopping List", general_shopping_list_index_path, method: :get, class: 'btn btn-outline-primary me-4' %>
    <%= button_to "Add Ingredient", new_recipe_recipe_food_path(@recipe), method: :get, class: "btn btn-dark" %>
  </div>
  <br/>
<% end %>

  <table class="table table-hover table-striped table-bordered">
    <thead class="table-dark">
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Value</th>
        <% if can? :manage, @recipe %>
          <th scope="col">Actions</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @recipe_foods.includes(:food).each do |item| %>
        <tr>
          <td><%= item.food.name%></td>
          <td><%= item.quantity%> <%= item.food.measurement_unit%></td>
          <td>$<%= item.food.price * item.quantity%></td>
          <% if can? :manage, @recipe %>
            <th scope="row d-flex ">
                <%= link_to "Modify", edit_recipe_food_path(item) %>
                <%= link_to "Delete", recipe_food_path(item), method: :delete, data: {turbo_method: :delete} %>
            </th>
          <% end %>
          
        </tr>
      <%end%>
    </tbody>
  </table>

<% end %>


<br/>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<p>Here is a list of recipes for a given user</p>
<br>

<%= button_to "New Recipe", new_user_recipe_path(@user.id), method: :get %>

<% if current_user == @user %>
  <div>
    <% @recipes.each do |recipe| %>
      <div class="recipe">
        <div>
          <p><a href="/recipes/<%= recipe.id %>/"> <%= recipe.name %> </a></p>
          <% if can? :manage, recipe %>
          <%= button_to "REMOVE", recipe_path(recipe.id), method: :delete, data: {confirm: "Are you sure you want to delete this recipe?"} %>
          <% end %>
        </div>
        <p><a href="/recipes/<%= recipe.id %>/"> <%= recipe.description %> </a></p>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="recipe">
    <p>Unavaliable to you. Please log in as correct user to access.</p>
  </div>
<% end %>
        

app/views/recipes/new.html.erb
<h2>New Recipe</h2>
<br>

<div>
<%= form_with model: @recipe, method: :post, url: user_recipes_path do |form| %>
  <%= form.label :name %><br>
  <%= form.text_field :name %><br>

  <%= form.label :description %><br>
  <%= form.text_field :description %><br>

  <%= form.label :preparation_time %><br>
  <%= form.text_field :preparation_time %><br>

  <%= form.label :cooking_time %><br>
  <%= form.text_field :cooking_time %><br>

  <%= form.submit "Create Recipe" %><br>
  <%end%>
</div>

app/views/recipes/show.html.erb
<div class="jumbotron">

  <div class="d-flex justify-content-between align-items-center">
    <h1 class="display-4">
      <%= @recipe.name %>
    </h1>
    <% if can? :manage, @recipe %>
      <%= render 'public_btn', recipe: @recipe %>
    <% end %>
  </div>
  <p class="lead">
   Preparation time: <%= @recipe.preparation_time %><small>hrs</small>  |  Cooking time: <%= @recipe.cooking_time %><small>hrs</small>
  </p>
  <p><%= @recipe.description %></p>
  <br/>
  <%= render 'recipe_foods_table', locals: { recipe: @recipe, recipe_foods: @recipe_foods} %>
</div>