config/routes.rb
Rails.application.routes.draw do
  resources :recipe_foods
  devise_for :users
  resources :users, only:[:index], shallow: true do
    resources :foods, only: [:index, :create, :new, :destroy]
    resources :recipes
  end
  resources :recipes do
    resources :recipe_foods, only: [:index, :new, :create, :update, :destroy]
  end
  resources :general_shopping_list, only: [:index]
  resources :public_recipes, only: [:index]
  root to: "public_recipes#index"
end

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
  <div class="container-fluid container">
    <%= link_to "Recipe App", root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if user_signed_in?%>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Public Recipes", root_path, class: "nav-link"%>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Inventory
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "Food List", user_foods_path(current_user), class: "dropdown-item"%></li>
              <li><%= link_to "Recipes List", recipes_path(user_id: current_user), class: "dropdown-item"%></li>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Actions
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "Add Food", new_user_food_path(current_user), class: "dropdown-item"%></li>
              <li><%= link_to "Add Recipe", new_user_recipe_path(current_user), class: "dropdown-item"%></li>
            </ul>
          </li>
        </ul>
        <div class="d-flex">
          <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger' %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_notification.html.erb
<% flash.each do |type, msg| %>
<br/>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </div>
<% end %>
<br/>
<br/>