config/routes.rb
Rails.application.routes.draw do
  resources :recipe_foods
  devise_for :users
  resources :users, only:[:index], shallow: true do
    resources :foods, only: [:index, :create, :new, :destroy]
    resources :recipes
  end
  resources :recipes do
    resources :recipe_foods, only: [:index, :new, :create, :update, :destroy]
  end
  resources :general_shopping_list, only: [:index]
  resources :public_recipes, only: [:index]
  root to: "public_recipes#index"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, foreign_key: :food_id, dependent: :destroy

  validates :name, presence: true, length: { maximum: 250 }
  validates :measurement_unit, presence: true, length: { maximum: 250 }
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @foods = @user.foods || []
  end

  def new
    @food = Food.new
    session[:referer] ||= request.referer
  end

  def create
    user = User.find(params[:user_id])
    food = user.foods.build(food_params)
    if food.save
      redirect_to session.delete(:referer) || user_foods_path(current_user),
                  notice: 'The food was saved successfully!'
    else
      flash[:error] = 'Could not save the food!'
      redirect_to new_user_food_path(current_user)
    end
  end

  def destroy
    food = Food.find(params[:id])
    food.destroy
    redirect_to user_foods_path(current_user), notice: 'The food was deleted successfully!'
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/helpers/food_helper.rb
module FoodHelper
end

app/views/foods/_form.html.erb
<%= form_with(model: food, url: user_foods_path, local: true) do |f| %>
   <div class="form-group">
        <%= f.label :name%>
        <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
    </div>
    <br/>

    <div class="form-group">
        <%= f.label :measurement_unit %>
        <%= f.text_field :measurement_unit, class: "form-control", placeholder: "Measurement Unit"  %>
    </div>
    <br/>

    <div class="form-group">
        <%= f.label :price %>
        <%= f.text_field :price,  class: "form-control", placeholder: "Price"  %>
    </div>
    <br/>

    <div class="form-group">
        <%= f.label :quantity %>
        <%= f.text_field :quantity,  class: "form-control", placeholder: "Quantity"  %>
    </div>
    <br/>
     <%= f.submit "Add Food", class: "btn btn-dark" %>
<% end %>

app/views/foods/index.html.erb
<% if @foods.empty? %>
  <p class="text-primary">No foods added yet!</p>

<% else %>
  <div class="d-flex justify-content-end"> 
  <%= button_to "Add Food", new_user_food_path(@user.id), method: :get, class: "btn btn-dark" %>
  </div>
  <br/>

  <table class="table table-hover table-striped table-bordered">
    <thead class="table-dark">
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Available Units</th>
        <th scope="col">Measurement Unit</th>
        <th scope="col">Unit Price</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |item| %>
        <tr>
          <td><%= item.name%></td>
          <td><%= item.quantity%></td>
          <td><%= item.measurement_unit%></td>
          <td>$<%= item.price%></td>
          <th scope="row">
          <%= link_to "Delete", food_path(item), method: :delete,  data: {turbo_method: :delete} %>
          </th>
        </tr>
      <%end%>
    </tbody>
  </table>
<% end %>

app/views/foods/new.html.erb
<h2>Add Food Item</h2>
<br/>
<%= render 'form', food: @food %>

<br/>
<%= link_to 'Cancel', session.delete(:referer), class:"btn btn-secondary" %>